apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  # namespace: dev
  labels:
    app: k8s-frontend
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: k8s-frontend
  template:
    metadata:
      labels:
        app: k8s-frontend
    spec:
      containers:
      - name: k8s-frontend
        image: giangle197/todolist-fe 
        ports:
        - containerPort: 3001 
        # restartPolicy: Always
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef: 
              name: web-configmap
              key: backend_url

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  # namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backend
  template:
    metadata:
      labels:
        app: k8s-backend
    spec:
      containers:
      - name: k8s-backend
        image: giangle197/todolist-be
        resources:
          requests:
            cpu: 10m
        ports:
        - containerPort: 3000
        # restartPolicy: Always
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: database_url
        - name: DB_DATABASE 
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: database
        - name: DB_USERNAME 
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_password
        # - name: Api__Protocol
        #   valueFrom:
        #     configMapKeyRef:
        #       name: api-configmap
        #       key: api_protocol
        # - name: Api__Host
        #   valueFrom:
        #     configMapKeyRef:
        #       name: api-configmap
        #       key: api_host
        # - name: Api__Port
        #   valueFrom:
        #     configMapKeyRef:
        #       name: api-configmap
        #       key: api_port
