apiVersion: v1
kind: Secret
metadata: 
  name: mysql-secret
  # namespace: dev
type: Opaque
data: 
  db_user: cm9vdA== # base64 encoded value of 'root'
  db_password: YWRtaW4xMjM0NSQ= # base64 encoded value of 'admin12345$'
