version: '3.8'

services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=gianglv6
      - MYSQL_ROOT_PASSWORD=admin123@
    ports:
      - '3306:3306'
    expose: 
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST='database-mysql'
      - URL_REACT=http://localhost
      # - DB_HOST=host.docker.internal
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - database-mysql


  frontend:
    build:
      context: ../vue
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - VITE_APP_API_BASE_URL=http://backend:3000
    ports:
      - 8080:80
    expose:
      - 8080

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
